[package]
name = "iota-core"
version = "0.2.0-alpha.3"
authors = ["YuWeiWu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Core library of IOTA"
license = "Apache-2.0"

[lib]
name = "iota"

[dependencies]
bee-message = { git = "https://github.com/wusyong/bee-p.git", branch = "bee-message" }
bee-signing-ext = { git = "https://github.com/wusyong/bee-p.git", branch = "sign-ext" }
iota-client = { version = "0.5.0-alpha", path = "../iota-client" }

[dev-dependencies]
tokio = { version = "0.2.22", features = ["macros"] }
