[package]
name = "iota-core"
version = "0.2.0-alpha.3"
authors = ["YuWeiWu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Core library of IOTA"
license = "Apache-2.0"

[features]
default = ["ureq"]
ureq = ["iota-client/ureq"]
surf-curl = ["iota-client/surf-curl"]
surf-wasm = ["iota-client/surf-wasm"]

[lib]
name = "iota"

[dependencies]
bee-transaction = { git = "https://github.com/Alex6323/bee-p.git", branch = "master"}#, rev = "02965e78a5cd43d0fb773771470ab3d891066562" }#
bee-ternary = { version = "0.4.1-alpha", git = "https://github.com/iotaledger/bee.git", features = ["serde1"], branch = "dev"}#, rev = "612fa2b9547c10f0c03a947d491db228af0fdabf" }#
bee-signing = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-crypto = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
iota-client = { path = "../iota-client", default-features = false }

#[features]
#quorum = ["iota-client/quorum"]
#wasm = ["iota-client/wasm"]
