[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"

[dev-dependencies]
tokio = { version = "1.1", features = ["full"] }
# add `, features = ["mqtt"]` for the mqtt example
iota-core = { path = "../iota-core", features = ["storage"] }
hex = "0.4.2"
dotenv = "0.15.0"

# [[example]]
# name = "mqtt"
# path = "mqtt.rs"

[[example]]
name = "address"
path = "address.rs"

[[example]]
name = "balance"
path = "balance.rs"

[[example]]
name = "indexation"
path = "indexation.rs"

[[example]]
name = "transaction"
path = "transaction.rs"

[[example]]
name = "multiple_outputs"
path = "multiple_outputs.rs"

[[example]]
name = "custom_inputs"
path = "custom_inputs.rs"

[[example]]
name = "custom_payload"
path = "custom_payload.rs"

[[example]]
name = "search_address"
path = "search_address.rs"

[[example]]
name = "custom_parent"
path = "custom_parent.rs"

[[example]]
name = "dust"
path = "dust.rs"

[[example]]
name = "nodeinfo"
path = "nodeinfo.rs"

[[example]]
name = "txspam"
path = "txspam.rs"

[[example]]
name = "storage"
path = "storage.rs"

[[example]]
name = "peers"
path = "peers.rs"

[[example]]
name = "message_time"
path = "message_time.rs"
