[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"

[dev-dependencies]
tokio = { version = "0.2.22", features = ["full"] }
iota-core = { path = "../iota-core"}

[[example]]
name = "address"
path = "address.rs"

[[example]]
name = "balance"
path = "balance.rs"

[[example]]
name = "transaction"
path = "transaction.rs"
