[package]
name = "iota-validation"
version = "0.2.1"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Validators used by Iota"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-validation"
license = "MIT"

[lib]
name = "iota_validation"
path = "lib.rs"

[dependencies]
iota-model = { version = "0.3.0", path = "../iota-model" }
iota-crypto = { version = "0.3.0", path = "../iota-crypto" }
iota-conversion = { version = "0.3.0", path = "../iota-conversion" }
iota-constants = { version = "0.2.1", path = "../iota-constants" }
lazy_static = "1.3"
regex = "1.1"
failure = "0.1"