
name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set current week of the year in environnement
        run: echo "::set-env name=CURRENT_WEEK::$(date +%V)"
      
      - name: Cache .rustup
        uses: actions/cache@v1
        with:
          path: ~/.rustup
          key: rustup-${{ env.CURRENT_WEEK }}-clippy
      
      - name: Cache cargo binaries
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: cargo-binaries-${{ env.CURRENT_WEEK }}-clippy
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set current week of the year in environnement
        run: echo "::set-env name=CURRENT_WEEK::$(date +%V)"

      - name: Cache cargo binaries
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: cargo-binaries-${{ env.CURRENT_WEEK }}-loc
      
      - name: Install cargo-count
        run: cargo install cargo-count || true

      - name: Run cargo count
        # '-a --exclude=$(cat .gitignore)' necessary to work around:
        # https://github.com/kbknapp/cargo-count/issues/36
        run: cargo count -l rs -a --exclude=$(cat .gitignore) src