name: Test Docs Build

on:
  pull_request:
    branches:
      - develop

concurrency: 
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Build
        run: |
          cd documentation
          yarn install --immutable
          yarn build
