[package]
name = "iota-client"
version = "0.5.0-alpha.3"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Client to use Iota APIs"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-client"
license = "Apache-2.0"

[lib]
name = "iota_client"

[dependencies]
iota-bundle-miner = { path = "../iota-bundle-miner" }

bee-transaction = { git = "https://github.com/Alex6323/bee-p.git", rev = "cf47287dbb37861668d378ea3ae3b8c0f2852566" }
bee-ternary = { version = "0.4.2-alpha", features = ["serde1"] }
#reqwest = { version = "0.10.6", features = ["json", "rustls-tls", "native-tls-vendored", "blocking"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.12"
ureq = { version = "2.0", features = ["json"] }
#chrysalis2
bee-common-derive = "0.1.1-alpha"
slip10 = "0.4"
iota-crypto = { version = "0.5.0", features = ["ed25519", "random", "wots_deprecated_do_not_use", "kerl_deprecated_do_not_use"] }
blake2 = "0.9"
bee-message = "0.1.1"
bee-common = "0.4.1"
hex = "0.4.2"
tokio = { version = "1.4", features = ["sync"] }

#quorum
once_cell = "1.7.2"

#pow
iota-model = {git = "https://github.com/iotaledger/iota.rs", rev = "0aa7e11b075bea17ae52b1f7dff51f3a13c9d914"}
num_cpus = "1.10"
crossbeam = "0.7"
failure = "0.1"
iota-conversion = "0.5"

[dev-dependencies]
anyhow = "1.0.31"
smol = {version = "0.1.18", features = ["tokio02"] }
smol-potat = "0.3.3"

