[package]
name = "iota-client"
version = "0.5.0-alpha.3"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Client to use Iota APIs"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-client"
license = "Apache-2.0"

[lib]
name = "iota_client"

[features]
default = ["ureq"]
surf-curl = ["surf", "surf/curl-client"]
surf-wasm = ["surf", "surf/wasm-client"]

[dependencies]
bee-transaction = { git = "https://github.com/Alex6323/bee-p.git", branch = "master"}#, rev = "02965e78a5cd43d0fb773771470ab3d891066562" }#
bee-ternary = { version = "0.4.1-alpha", git = "https://github.com/iotaledger/bee.git", features = ["serde1"], branch = "dev"}#, rev = "612fa2b9547c10f0c03a947d491db228af0fdabf" }#
bee-signing = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-crypto = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
#reqwest = { version = "0.10.6", features = ["json", "rustls-tls", "native-tls-vendored", "blocking"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.12"
ureq = { version = "1.5.1", features = ["json"], optional = true }
surf = { version = "2.1.0", default-features = false, features = [], optional = true }#"default-client"

[dev-dependencies]
anyhow = "1.0.31"
smol = {version = "0.1.18", features = ["tokio02"] }
smol-potat = "0.3.3"

#[features]
#quorum = ["smol"]
#wasm = ["chrono/wasmbind"]

#[[test]]
#name = "quorum"
#required-features = ["quorum"]
