[package]
name = "iota-client"
version = "0.3.0"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Client to use Iota APIs"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-client"
license = "MIT"

[lib]
name = "iota_client"
path = "lib.rs"

[dependencies]
reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
failure = "0.1"
iota-model = { version = "0.3.0", path = "../iota-model" }
iota-conversion = { version = "0.3.0", path = "../iota-conversion" }
iota-pow = { version = "0.2.1", path = "../iota-pow" }
iota-validation = { version = "0.2.1", path = "../iota-validation" }
iota-signing = { version = "0.2.1", path = "../iota-signing" }
iota-constants = { version = "0.2.1", path = "../iota-constants" }
iota-utils = { version = "0.2.1", path = "../iota-utils" }
chrono = "0.4"
lazy_static = "1.3"
tokio = "0.1.21"
tokio-threadpool = "0.1.14"
num_cpus = "1.10"