[package]
name = "iota-client"
version = "0.5.0-alpha.3"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Client to use Iota APIs"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-client"
license = "Apache-2.0"

[lib]
name = "iota_client"

[dependencies]
bee-common = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-message = { git = "https://github.com/iotaledger/bee.git", branch = "chrysalis-pt-2" }
bee-pow = { git = "https://github.com/iotaledger/bee.git", branch = "chrysalis-pt-2" }
bee-signing = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-signing-ext = { git = "https://github.com/wusyong/bee-p.git", branch = "sign-ext" }
bee-crypto = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
reqwest = { version = "0.11", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.58"
chrono = "0.4.12"
hex = "0.4.2"
blake2 = "0.9"
paho-mqtt = { version = "0.8", optional = true }
regex = "1.4"
tokio = { version = "1.0.0", features = ["macros", "sync", "rt-multi-thread"] }
thiserror = "1.0"
num_cpus = "1.13"

[features]
default = ["mqtt"]
mqtt = ["paho-mqtt"]
