[package]
name = "iota-client"
version = "0.5.0-alpha.3"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Client to use Iota APIs"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-client"
license = "MIT"

[lib]
name = "iota_client"
path = "lib.rs"

[dependencies]
bee-transaction = { git = "https://github.com/Alex6323/bee-p.git" }
bee-ternary = { version = "0.1.0-alpha", git = "https://github.com/iotaledger/bee.git", features = ["serde1"] }
bee-signing = { git = "https://github.com/Alex6323/bee-p.git" }
bee-crypto = { git = "https://github.com/Alex6323/bee-p.git" }
iota-conversion = { version = "0.5.1", path = "../iota-conversion" }
reqwest = { version = "0.10.6", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.12"
once_cell = "1.4.0"
smol = {version = "0.1.18", features = ["tokio02"], optional = true }

[dev-dependencies]
anyhow = "1.0.31"
smol = {version = "0.1.18", features = ["tokio02"] }
smol-potat = "0.3.3"

[features]
quorum = ["smol"]
wasm = ["chrono/wasmbind"]

[[test]]
name = "quorum"
required-features = ["quorum"]