[package]
name = "iota-client"
version = "0.5.0-alpha.3"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Client to use Iota APIs"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-client"
license = "Apache-2.0"

[lib]
name = "iota_client"

[dependencies]
bee-transaction = { git = "https://github.com/Alex6323/bee-p.git", rev = "02965e78a5cd43d0fb773771470ab3d891066562" }
bee-ternary = { version = "0.4.0-alpha", git = "https://github.com/iotaledger/bee.git", branch = "dev", features = ["serde1"] }
bee-signing = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-crypto = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
#reqwest = { version = "0.10.6", features = ["json", "rustls-tls", "native-tls-vendored", "blocking"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.12"
ureq = { version = "1.5.1", features = ["json"] }
#chrysalis2
bee-common-derive = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
slip10 = "0.4"
iota-crypto = { git = "https://github.com/iotaledger/crypto.rs.git", rev = "6e67b652dd55df05877f575b9a09ccb5a7006694", features = ["ed25519", "random"]}
blake2 = "0.9"
bee-message = { git = "https://github.com/iotaledger/bee.git", branch = "chrysalis-pt-2" }
bee-common = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
hex = "0.4.2"

#pow
iota-model = {git = "https://github.com/iotaledger/iota.rs", rev = "0aa7e11b075bea17ae52b1f7dff51f3a13c9d914"}
num_cpus = "1.10"
crossbeam = "0.7"
failure = "0.1"
iota-conversion = "0.5"

[dev-dependencies]
anyhow = "1.0.31"
smol = {version = "0.1.18", features = ["tokio02"] }
smol-potat = "0.3.3"

#[features]
#quorum = ["smol"]
#wasm = ["chrono/wasmbind"]

#[[test]]
#name = "quorum"
#required-features = ["quorum"]
