[package]
name = "iota-client"
version = "0.5.0-alpha.2"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Client to use Iota APIs"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-client"
license = "MIT"

[lib]
name = "iota_client"
path = "lib.rs"

[dependencies]
reqwest = { version = "0.10.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.26"
chrono = "0.4.11"
iota-bundle-preview = "0.1"
iota-ternary-preview = "0.1"
iota-signing-preview = "0.1"
iota-crypto-preview = "0.1"
iota-conversion = { version = "0.5.1", path = "../iota-conversion" }
once_cell = "1.4.0"
slab = "0.4.2"

[dev-dependencies]
smol = {version = "=0.1.7", features = ["tokio02"] }
smol-potat = "0.2.1"

[features]
wasm = ["chrono/wasmbind"]
