[package]
name = "iota-client"
version = "0.3.0"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Client to use Iota APIs"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-client"
license = "MIT"

[lib]
name = "iota_client"
path = "lib.rs"

[dependencies]
reqwest = { version = "0.10.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.26"
chrono = "0.4.11"
tokio = { version = "0.2.9", features = ["macros"] }
bee-bundle = { git = "https://github.com/Alex6323/bee-p" }
bee-ternary = { git = "https://github.com/Alex6323/bee-p" }
bee-signing = { git = "https://github.com/Alex6323/bee-p" }
bee-crypto = { git = "https://github.com/Alex6323/bee-p" }
iota-conversion = { version = "0.3.0", path = "../iota-conversion" }
