[package]
name = "iota-client"
version = "0.5.0-alpha.3"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
description = "Client to use Iota APIs"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://github.com/iotaledger/iota.rs"
documentation = "https://docs.rs/iota-client"
license = "Apache-2.0"

[lib]
name = "iota_client"

[dependencies]
# bee-rest-api = { git = "https://github.com/iotaledger/bee.git", branch = "chrysalis-pt-2" }
# bee-message = { git = "https://github.com/iotaledger/bee.git", branch = "chrysalis-pt-2" }
# bee-pow = { git = "https://github.com/iotaledger/bee.git", branch = "chrysalis-pt-2" }
# bee-common-derive = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
# bee-crypto = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-rest-api = { git = "https://github.com/iotaledger/bee.git", rev = "acab07e4bcff947c70cde312789a2ef2977c652b" }
bee-message = { git = "https://github.com/iotaledger/bee.git", rev = "acab07e4bcff947c70cde312789a2ef2977c652b" }
bee-pow = { git = "https://github.com/iotaledger/bee.git", rev = "acab07e4bcff947c70cde312789a2ef2977c652b" }
bee-common = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-crypto = { git = "https://github.com/iotaledger/bee.git", rev = "c42171ff33c80cc2efb183e244dc79b7f58d9ac4" }
iota-crypto = { git = "https://github.com/iotaledger/crypto.rs.git", rev = "527392202e78fa35620a9b30061d5e231a046ea2", features = ["blake2b", "ed25519", "random", "slip10"]}
ureq = { version = "2.0", features = ["json"] }
url = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4"
tokio = { version = "1.1", features = ["macros", "sync", "rt-multi-thread"] }
thiserror = "1.0"
num_cpus = "1.13"
rusqlite = { version = "0.24", features = ["bundled"], optional = true }
async-trait = "0.1"

# MQTT
paho-mqtt = { version = "0.9", optional = true }
regex = { version = "1.4", optional = true }
once_cell = { version = "1.5", optional = true }
futures = { version = "0.3", optional = true }

[features]
mqtt = ["paho-mqtt", "regex", "once_cell", "futures"]
storage = ["rusqlite", "once_cell"]